WritingShop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = []

urlpatterns += [ path('favicon.ico', RedirectView.as_view(url=settings.MEDIA_URL + 'main/favicon.png')) ]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('_App.urls')),
    # path('', include('_App.urls_api')),
]

_App/urls.py
from django.conf.urls import url
from django.contrib.auth import views
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = 'App'

urlpatterns = [
    url(
        regex=r'^home/signup/',
        view=views.SignUp.as_view(),
        name='signup', #회원가입
    ),
    url(
        regex=r'home/list/create/',
        view=views.ListCreatePage.as_view(),
        name='list_create', # 리스트 생성 페이지
    ),
    url(
        regex=r'home/list/search/',
        view=views.ListSearchPage.as_view(),
        name='list_search', # 리스트 검색 페이지
    ), 
    url(
        regex=r'^home/list/(?P<post_id>[0-9]+)/',
        view=views.ListDetailPage.as_view(),
        name='post_detail', #리스트 디테일 페이지
    ),
    url(
        regex=r'home/list/',
        view=views.ListPage.as_view(),
        name='list', # 리스트페이지
    ),
    url(
        regex=r'home/',
        view=views.HomePage.as_view(),
        name='home', # 메인페이지
    ),
    url(
        regex=r'',
        view=views.StartPage.as_view(),
        name='start', # 시작페이지
    ), 
]


templates/Home/Home.html
{% extends "Base/Base.html" %}
{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'Home/css/style.css' %}">
<div class="jumbotron">
	<div class="jumbotron-inner">
		<div class="invitation">
			<p class="invitation-text-md">오늘의 기분은 어떠신가요?</p>
			<h1 class="invitation-heading">글로써 삶의 길을 살아가요</h1>
			<p class="invitation-text-sm"> 
        <a class="btn btn-info" href="{% url 'App:list_search' %}">검색하기</a>
        <a class="btn btn-info" href="{% url 'App:list_create' %}">글귀작성</a>
      </p>
		</div>
	</div>
</div>
    <div class="container">
      <div class="row">
        {% for writePostData in writePostDatas %}
          <div class="col-4.5">
            <div class="card bg-light mb-3" style="max-width: 20rem;">
              <div class="card-body">

                  <h6 class="img_li"><a href='home/list/{{ writePostData.pk }}/'><img id="im" src="/media/{{ writePostData.images }}" style="width: 280px;"></a></h6>

                  <p class="project-skills-tag-viewbox">
                    {% for tag in writePostData.tags.all %}
                      <span class="skills-tag">{{tag}}</span>
                    {% endfor %}
                    ...
                  </p>
              
               </div>
             </div>
            </div>
          {% endfor %}
        </div>
      </div>
{% endblock%}