WritingShop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = []

urlpatterns += [ path('favicon.ico', RedirectView.as_view(url=settings.MEDIA_URL + 'main/favicon.png')) ]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('_App.urls')),
    # path('', include('_App.urls_api')),
]

_App/urls.py
from django.conf.urls import url
from django.contrib.auth import views
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = 'App'

urlpatterns = [
    url(
        regex=r'^home/signup/',
        view=views.SignUp.as_view(),
        name='signup', #회원가입
    ),
    url(
        regex=r'home/list/create/',
        view=views.ListCreatePage.as_view(),
        name='list_create', # 리스트 생성 페이지
    ),
    url(
        regex=r'home/list/search/',
        view=views.ListSearchPage.as_view(),
        name='list_search', # 리스트 검색 페이지
    ), 
    url(
        regex=r'^home/list/(?P<post_id>[0-9]+)/',
        view=views.ListDetailPage.as_view(),
        name='post_detail', #리스트 디테일 페이지
    ),
    url(
        regex=r'home/list/',
        view=views.ListPage.as_view(),
        name='list', # 리스트페이지
    ),
    url(
        regex=r'home/',
        view=views.HomePage.as_view(),
        name='home', # 메인페이지
    ),
    url(
        regex=r'',
        view=views.StartPage.as_view(),
        name='start', # 시작페이지
    ), 
]


templates/Start/Start.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">
  <head>
    <link rel="stylesheet" type="text/css" href="{% static 'Start/css/style.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Gothic+A1" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    <meta charset="utf-8">
    <title>글길</title>
  </head>
  <body>
    <div class="container-fluid">
      <div id="il"></div>
      <div class="center-block" id="text">
        <div class="center-block" id="box">
          <div class="img-responsive center-block" id="log">
            <img src="/media/Main/logo_white.png">
          </div>
          <div class="center-block" id="fonl">
            <p id="fon">글로써 삶의 길을 살아가자</p>
          </div>
        </div>
        <div class="center-block" id="buu">
          <a class="navbar-brand" href="{% url 'App:home' %}"><button type="button">시작하기</button></a>
        </div>
      </div>
    </div>
  </body>
</html>